sudo: required

services:
  - docker

before_install:
  - sudo apt-get update -y --allow-unauthenticated
  - sudo apt-get install -y docker-engine

before_script:
  - docker build -t deeky666/base .

script:
  - docker run deeky666/base true

after_success:
  - if [ ! -z "$TRAVIS_TAG" ]; then docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push deeky666/base; fi
